### ISSUE TITLE
Undefined method during database seed

### ISSUE THREAD

**Issue by afestein** [kortirso/pullmetry#277]
Hello, thanks for making this open source ❤️

During the setup process `rails db:seed` I'm seeing the following error:

```
NoMethodError: undefined method `call' for Identities::CreateForm:Class (NoMethodError)

  Identities::CreateForm.call(
                        ^^^^^
/Users/afestein/code/pullmetry/db/seeds.rb:140:in `block in <main>'
/Users/afestein/code/pullmetry/db/seeds.rb:129:in `times'
/Users/afestein/code/pullmetry/db/seeds.rb:129:in `<main>'
```

**Comment by kortirso** [comment]
@afestein thank you for commenting, I had fixed seeds
